# This is a basic workflow to help you get started with Actions

name: Run another workflow file on create tags

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run on create tags
          token: ${{ secrets.PERSONAL_TOKEN }}
